name: zGamemode
version: 0.5
main: com.zp4rker.zgamemode.zGamemode
commands:
  creative:
    aliases: c
    usage: ยง2/<command> <PLAYER>
    permission: zgm.creative
  survival:
      aliases: s
      usage: ยง2/<command> <PLAYER>
      permission: zgm.survival
  adventure:
        aliases: a
        usage: ยง2/<command> <PLAYER>
        permission: zgm.adventure