name: zConomy
version: 1.0
author: ZP4RKER
main: com.zp4rker.zconomy.zConomy
database: true
description: A currency plugin
commands:
    balance:
        description: Displays a players balance
        usage: ยง2/balance <PLAYER>
    setmoney:
        description: Sets a players balance
        usage: ยง2/setmoney <PLAYER> <AMOUNT>
    givemoney:
        description: Gives a player a certian amount of money
        usage: ยง2/givemoney <PLAYER> <AMOUNT>
    pay:
        description: Pays a player
        usage: ยง2/pay <PLAYER> <AMOUNT>