name: zRanks
version: 1.0
author: ZP4RKER
main: com.zp4rker.zranks.zRanks
commands:
    setrank:
       usage: ยง2/setrank <PLAYER> <RANK>
       description: Sets the rank of a player.
    who:
       usage: ยง2/who
       description: Displays all online players.
    staff:
       usage: ยง2/staff
       description: Displays all online staff members.