name: TheRetronixHUB
version: 0.1
main: com.theretronix.hubp.HUB
database: true
description: The Retronix Hub Plugin
author: ZP4RKER
commands:
    server:
        usage: /server <Server>
        description: Connects the player to the specified server.