Player Join Message: '§e%player% joined the server!'
Player Quit Message: '§e%player% left the server!'
Server Welcome Message: '§5Welcome to our server!'
Server Welcome Title: '§5Welcome'
Server Welcome Subtitle: '§3%player%'
Player Death Message: '§e%player% died!'
Gamemode Change Message: '§2You are now in §e%gamemode%'
Server Broadcast Prefix: '§4[§eBroadcast§4]'
Kick Prefix: '§e[§3My Server§e]'
Ban Prefix: '§e[§3My Server§e]'
Chat Format: '%displayname% §7: §r%message%'
