name: zNexusFactions
version: 0.1
author: ZP4RKER
main: zplugin.znexusfactions.zNexusFactions
database: true
commands:
    zfactions:
        usage: ยง2/zfactions <FUNCTION> [ARGUMENTS]
        aliases: [zf, znf, nf]
        description: Base command